"project_id": "8"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."
"preserve_hierarchy": true

"files": [
  {
    "source": "/locales/en.json",
    "translation": "/locales/%two_letters_code%.json"
  }
]
