"project_id": "8"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."
"base_url": "https://mktraining.api.crowdin.com"
"preserve_hierarchy": true

"files": [
  {
    "source": "/locales/en.po",
    "translation": "/locales/%two_letters_code%.po"
  },
  {
    "source": "/locales/en.strings",
    "translation": "/locales/%two_letters_code%.strings"
  },
  {
    "source": "/locales/large_en.json",
    "translation": "/locales/large_%two_letters_code%.json"
  }
]
